### ISSUE TITLE
Accessibility: prefers reduced motion

### ISSUE THREAD

**Issue by SheepTester** [cse110-sp23-group20/fortune-teller#83]
Disable most animations or transitions with

```css
* {
  transition: none !important;
  animation: none !important;
}
```

when [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) is on
